### ISSUE TITLE
Vulnerabilities in Firebase Database Rules 

### ISSUE THREAD

**Issue by omer88** [Methodician/ScatterSchool#56]
There is a security issue with the current Firebase Database Rules:

An attacker can arbitrarily write data under `/chatData`.
This is due to a misconfigured write rule - `".write": "auth.uid != null"` under `/chatData`.

A more elaborated explanation of the vulnerability can be found [here](https://noless.io/report/-L7Q7rHsU-q5pLWltM35/c8a0eaf7-662d-430c-8243-1d2c8e68327b).

The suggested solution is to remove this rule from `/chatData` , but in order not to break any functionality, each path under `/chatData` should be specified with the appropriate rules.

In order to generate another report, after fixing the issue, you can login into https://noless.io.

**Comment by Methodician** [comment]
Thanks for bringing these things to our attention. We left some mess in our rules document! We're clearing that up...

I'm interested to see where your startup goes....
